### ISSUE TITLE
Un exercice vec juste un titre et une intro plante bizarrement

### ISSUE THREAD

**Issue by forax** [PremierLangage/premierlangage#186]
avec la feuille.pltp:

title= foo
introduction==
  fmfdfdmkfdsmkfmkslmgfdv, lmsv,ffdkg
==

Cela affiche:

list index out of range

Traceback (most recent call last):
  File "/srv/local/pl/premierlangage/server/serverpl/playexo/models.py", line 362, in get_exercise
    dic['first_pl__'] = self.session_activity.activity.pltp.pl.all()[0].id
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

**Comment by nimdanor** [comment]
The parser should test if the list of exercices is not empty
