### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'manage.py'

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/premierlangage#33]
When browsing through the filbrowser, this error sometimes occurs:

```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 98, in handle
    self.run(**options)
  File "/home/sedin/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 105, in run
    autoreload.main(self.inner_run, None, options)
  File "/home/sedin/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 317, in main
    python_reloader(wrapped_main_func, args, kwargs)
  File "/home/sedin/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 296, in python_reloader
    reloader_thread()
  File "/home/sedin/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 274, in reloader_thread
    change = fn()
  File "/home/sedin/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 204, in code_changed
    stat = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'manage.py'
```

This error is present in every branches since almost 1 year and I can't manage to track it down.
It's probably an `os.chdir` not well handled by a *try/finally* but I could not find it.

Even thought it's not a problem when the server is deployed, it's super annoying when working in local.

I'm ready to offer a kebab to anybody who manage to fix this :)

**Comment by nimdanor** [comment]
Question si l'on appel avec 
```
./manage.py runserver 
```
a t'on le meme problem
